export const moduleRoadmap = [
  { name: "POS & Sales", status: "live" as const, priority: 1 },
  { name: "Inventory FIFO", status: "live" as const, priority: 2 },
  { name: "Formula / BOM", status: "live" as const, priority: 3 },
  { name: "Production Orders", status: "live" as const, priority: 4 },
  { name: "Purchasing", status: "live" as const, priority: 5 },
  { name: "CRM", status: "live" as const, priority: 6 },
  { name: "Quotations", status: "live" as const, priority: 7 },
  { name: "Reporting", status: "live" as const, priority: 8 },
  { name: "RBAC & Security", status: "shell" as const, priority: 9 },
  { name: "Excel Import", status: "live" as const, priority: 10 },
  { name: "WhatsApp / Email", status: "live" as const, priority: 11 },
  { name: "Shopify", status: "planned" as const, priority: 12 },
  { name: "Accounting Sync", status: "planned" as const, priority: 13 },
];
